### ISSUE TITLE
jq 1.5 in Focal

### ISSUE THREAD

**Issue by Molkree** [travis-ci/travis-cookbooks#1091]
Ubuntu Focal has an old version of jq installed (1.5) which was unexpected for me considering the default in apt is 1.6. When digging a bit I found this repo and [recipe](https://github.com/travis-ci/travis-cookbooks/blob/master/cookbooks/travis_build_environment/recipes/jq.rb) for jq. I guess this is how it's being installed in all workers? Then I'd suggest updating to the latest release, I can file a PR if needed (just a one-character change).

**Comment by PeterDaveHello** [comment]
The response here doesn't seem to be quick, maybe can just send a PR and ask if the maintainer can help merge it will be faster 😄
