### ISSUE TITLE
mysql strict mode issues with standard rails apps?

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-cookbooks#136]
A customer on pro is having issues with running migrations for a standard rails app on mysql:

```
Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO `schema_migrations` (`version`) VALUES ('20100402170213')
```

From travis.yml

```
language: ruby
rvm:
- "1.9.3-p327"
services:
- mysql
script:
- bundle exec rspec
before_script:
- mysql -e 'create database [db_name];'
- bundle exec rake db:migrate
env:
- RAILS_ENV=test
```

Possibly related: https://github.com/rails/rails/pull/6069

Is it possible to switch mysql at runtime to not use strict mode?

Generally, if Rails actually is having issues with this we might want to consider turning it off?

**Comment by PowerKiKi** [comment]
The easiest to disable strict mode is:

```yml
before_script:
  - mysql -e 'CREATE DATABASE myDatabaseName; SET GLOBAL sql_mode = "";'
```
