### ISSUE TITLE
rabbitmq-management-plugin support

### ISSUE THREAD

**Issue by dreid** [travis-ci/travis-cookbooks#8]
The rabbitmq management plugin available here: http://www.rabbitmq.com/management.html provides a convenient REST api for creating virtualhosts. gen_bunny uses this to isolate test cases in it's integration tests, so it'd be useful if it were available in the  travis-ci rabbitmq install.  There are probably other use cases as well.

**Comment by joniba** [comment]
is there a workaround for this? how would I enable the management plugin manually on travis?
