### ISSUE TITLE
Unrelated /etc/profile.d/ script errors during APT addon usage

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-cookbooks#862]
Whilst looking into https://github.com/travis-ci/apt-source-whitelist/pull/291#issuecomment-295876207 I noticed that there were unrelated errors in the APT output during the installation of mysql 5.7:
```
mkdir: cannot create directory ‘//.pyenv’: Permission denied
mkdir: cannot create directory ‘//.pyenv’: Permission denied
```
(eg https://travis-ci.org/mozilla/treeherder/jobs/250567379#L511)

These appear to be due to the install sequence (which amongst other things runs commands like `invoke-rc.d mysql stop`) triggering the scripts in `/etc/profile.d/`.

In the above case this was just the pyenv script:
https://github.com/travis-ci/travis-cookbooks/blob/be329608f411aa130cca4b1e7f61d8b02be32f25/cookbooks/travis_build_environment/templates/default/pyenv.sh.erb

...however when running locally using the `travisci/ci-garnet` Docker image, I see errors from other scripts too:
```
root@95b143df2058:/# invoke-rc.d mysql start
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
 * Starting MySQL database server mysqld
No directory, logging in with HOME=/
-su: 2: /etc/profile.d/perlbrew.sh: [[: not found
mkdir: cannot create directory ‘//.pyenv’: Permission denied
mkdir: cannot create directory ‘//.pyenv’: Permission denied
-su: 14: /opt/jdk_switcher/jdk_switcher.sh: [[: Permission denied
-su: 21: /opt/jdk_switcher/jdk_switcher.sh: [[: Permission denied
-su: 28: /opt/jdk_switcher/jdk_switcher.sh: [[: Permission denied
-su: 35: /opt/jdk_switcher/jdk_switcher.sh: [[: Permission denied
-su: 42: /opt/jdk_switcher/jdk_switcher.sh: [[: Permission denied
-su: 49: /opt/jdk_switcher/jdk_switcher.sh: [[: Permission denied
-su: 55: /opt/jdk_switcher/jdk_switcher.sh: [[: Permission denied
-su: 55: /opt/jdk_switcher/jdk_switcher.sh: [[: Permission denied
-su: 55: /opt/jdk_switcher/jdk_switcher.sh: [[: Permission denied
                                                                                             [ OK ]
```

These aren't actually causing any problems, but can add confusion when debugging.

Perhaps the commands within the scripts should be piped to /dev/null, or else they have some more conditionals added to verify they are running as the expected user?

**Comment by meatballhat** [comment]
I _think_ this should be better now that #872 is merged, but please holler if you see otherwise.

**Comment by edmorley** [comment]
Awesome, thank you!
