### ISSUE TITLE
$JAVA_HOME isn't included in the $PATH anymore on Trusty with openjdk7

### ISSUE THREAD

**Issue by cotsog** [travis-ci/travis-cookbooks#875]
Stemming from [this ticket](https://secure.helpscout.net/conversation/401722726/57131/).

I did [a test build](https://travis-ci.org/cotsog/travis_ci_prod_regular/jobs/257870457#L432-L438) and I could see that $JAVA_HOME isn't included in $PATH anymore while it was [on Precise](https://travis-ci.org/cotsog/travis_ci_prod_regular/jobs/257870456#L231-L237).

Could you look into adding it back?

Thanks!

**Comment by cotsog** [comment]
FYI, it's also not included in sudo-enabled Trusty: https://travis-ci.org/cotsog/travis_ci_prod_regular/jobs/257870459#L442-L448

**Comment by cotsog** [comment]
Same thing with `jdk: openjdk8` on Trusty: https://travis-ci.org/cotsog/travis_ci_prod_regular/builds/257878002

**Comment by Lyoness** [comment]
For now, solution will be to prepend `$JAVA_HOME/bin` to `$PATH` at build time with `travis-build`

Investigation starts here with @BanzaiMan and me. 

https://travisci.slack.com/archives/C4GRZLLAE/p1501182806498179
