### ISSUE TITLE
The virtualenv.system_site_packages key doesn't work for new Trusty images

### ISSUE THREAD

**Issue by bogdanap** [travis-ci/travis-cookbooks#878]
Affected users that raised this issue:
https://secure.helpscout.net/conversation/401453294/57115/?folderId=30788
https://secure.helpscout.net/conversation/385229087/55722/?folderId=30784

It seems that the new Trusty images don't allow users to import system site packages, despite us still allowing this option in .travis.yaml.
Since there are users who have dependencies in PPAs, or just don't want to use pip, I think this option is worth keeping.

As a workaround until this is fixed, using "group:deprecated-2017Q2" should allow imports from site packages.

**Comment by bogdanap** [comment]
I've debugged this with both old and new builds and it seems that somewhere along the way, virtualenv stopped allowing access to system-site-packages.

As far as I can see the correct version is being sourced in the builds (`source ~/virtualenv/python2.7_with_system_site_packages/bin/activate`).

Also, when using /usr/local/bin/virtualenv instead of  /opt/python/2.7.13/bin/virtualenv the behaviour is correct.

**Comment by jjgreen** [comment]
I can confirm that the `group: deprecated-2017Q2` workaround is effective (the [commit](https://github.com/jjgreen/mvpoly/commit/9af81bb5e1f1ec545a5ef4c0d4b9c6912d00bb37) and the subsequent [Travis run](https://travis-ci.org/jjgreen/mvpoly/builds/260765222)), thanks!

**Comment by cas--** [comment]
I assume that you are now using a Python virtualenv from source (`/opt/python/2.7.13/bin/virtualenv`) so it will not have Ubuntu's patch to point to `dist-packages`.

A good detailed explanation: https://stackoverflow.com/questions/1215610/ubuntu-virtualenv-a-mess-virtualenv-hates-dist-packages-wants-site-package

Could use `.pth` as a solution e.g. https://stackoverflow.com/a/17265840/175584

**Comment by bogdanap** [comment]
@jjgreen @cas-- We're currently building the new images that include the fix. You should be able to test them later today by using `group: edge`.
Thank you again for raising this issue!

**Comment by jjgreen** [comment]
@bogdanap : fix [confirmed](https://travis-ci.org/jjgreen/mvpoly/builds/261130044), many thanks!
