### ISSUE TITLE
Consolidating versions across travis-cookbooks and packer-templates

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-cookbooks#897]
Currently version numbers for language runtimes (eg Python, nodejs, PHP) are split across the travis-cookbooks and packer-templates repositories.

This isn't ideal for a few reasons:
1) It's confusing for contributors (for example I initially thought travis-cookbooks was the source of truth, but it didn't match the version numbers I was seeing).
2) There are multiple repositories to keep in sync when bumping the version numbers.
3) Even between the attributes files in packer-templates there is duplication - eg between {amethyst, opal} and {garnet, sardonyx}.
4) It's not always clear what affect changing a version number in travis-cookbooks will have, since in some cases there is not a single image where that default is used, but in others the default is not overridden so does need more careful testing.

Instead I think it would make sense for travis-cookbooks to define named version ranges like `nodejs_lts_current`, `nodejs_lts_previous`, `nodejs_latest` etc - which can then be combined by the packer-templates overrides.

For example travis-cookbooks might default to just `nodejs_latest`, but both amethyst and opal could use `nodejs_lts_current` whilst garnet/sardonyx could use {`nodejs_lts_current` + `nodejs_latest`}. This would have the added bonus of making the version support policy more explicit.

@meatballhat, @Lyoness - thoughts? 😺

**Comment by meatballhat** [comment]
@edmorley I'm in favor of your named range solution 👍 🎉

**Comment by edmorley** [comment]
There also seem to be some examples of some languages being installed into multiple image types, possibly unintentionally - such as PHP, which exists in both {garnet, sardonyx} and {amethyst, opal} - except in the former it only has two versions installed (5.6.x and 7.0.x) whereas in the latter it has (5.6.x, 7.0.x and 7.1.x). This is because the {amethyst, opal} don't override the travis-cookbook defaults.

It seems like either the versions should match between the two images, or else one image should just contain one version and the other by the "multi-version variant".

This confusion is another reason why it would be good to fix this issue.
