### ISSUE TITLE
For HHVM, an older version of PHPUnit should be installed

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-cookbooks#908]
https://github.com/travis-ci/travis-cookbooks/blob/82e3307ec39f667c44117419760e0226c106f6a9/cookbooks/travis_build_environment/recipes/hhvm.rb#L55-L60

PHPUnit 6.0 [dropped PHP 5.6 support](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0#dropping-support-for-php-56). HHVM must stay with PHPUnit 5.7.

See https://github.com/travis-ci/travis-ci/issues/8516.

**Comment by bogdanap** [comment]
We've decided that, rather than revert to an older version of PHPUnit, we'd officially document the workaround.
