### ISSUE TITLE
Update phantomjs to 2.1.1

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-cookbooks#910]
http://phantomjs.org/download.html now has 2.1.1. It is best to have it pre-installed on our images. The current recipe installs the outdated (and custom-built) 2.0.0 https://github.com/travis-ci/travis-cookbooks/blob/280d0a5339a6c9369ffee34b107532068bf74e7a/cookbooks/travis_phantomjs/recipes/2.rb#L29-L42

**Comment by bogdanap** [comment]
Fixed by https://github.com/travis-ci/travis-cookbooks/pull/944
