### ISSUE TITLE
install dbus-x11 together with firefox

### ISSUE THREAD

**Issue by nkonev** [travis-ci/travis-cookbooks#911]
From https://github.com/travis-ci/travis-ci/issues/8520

In many latest builds I have 
```
(firefox:9067): GConf-WARNING **: Client failed to connect to the D-BUS daemon:

//bin/dbus-launch terminated abnormally without any error message
```

Although it don't fail build, it is too many spamming in console.

I investigated logs, so something happens 
between
https://travis-ci.org/nkonev/blog/builds/272661119 (ok)
https://travis-ci.org/nkonev/blog/builds/273055864 (spam)

As you can see, these builds from same github commit and same firefox version, so I think somebody changed ubuntu image what happen this firefox spamming.

After I'd [installed](https://github.com/nkonev/blog/compare/c9088ef9837e...44c7c1107ab6) `dbus-x11`
error [gone](https://travis-ci.org/nkonev/blog/builds/284907677).

Please add `dbus-x11` into image, firefox needs it.

**Comment by nkonev** [comment]
@BanzaiMan

**Comment by bogdanap** [comment]
Fixed in https://github.com/travis-ci/travis-cookbooks/pull/950
