### ISSUE TITLE
jdk_switcher doesn't switch between java versions

### ISSUE THREAD

**Issue by chandrams** [travis-ci/travis-cookbooks#913]
Opening an issue to track the jdk_switcher issue mentioned [here](https://github.com/travis-ci/travis-cookbooks/pull/874#issuecomment-334671006)

**Comment by bogdanap** [comment]
After some initial investigation, it seems that jdk_switcher behaves correctly and switches `/usr/bin/java` as expected, but our build images use `/usr/lib/jvm/<version>/java` instead.

Here is a build that demonstrates the problem: https://travis-ci.org/bogdanap/travis_production_test/builds/284273519

**Comment by chandrams** [comment]
Yes, tried this by setting PATH explicitly - https://travis-ci.org/chandrams/myproj/builds/285492338

I see PATH being set before it runs the .travis.yml and hence doesn't use /usr/bin/java 
 mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

$ export PATH=$JAVA_HOME/bin:$PATH
$ java -Xmx32m -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

whereas PATH was not set in the test cook book that I used for testing the recipes and jdk_switcher worked there -  https://travis-ci.org/chandrams/test-cookbook/builds/283544429

**Comment by chandrams** [comment]
Closing this based on above comment
