### ISSUE TITLE
Upgrade leiningen to >= 2.8

### ISSUE THREAD

**Issue by joepvd** [travis-ci/travis-cookbooks#924]
Currently on the Trusty images, Leiningen 2.7.1 is installed.

When combined with `oraclejdk9`, this is a [problem](https://github.com/technomancy/leiningen/issues/2149).

Please upgrade Leiningen to 2.8.* with any images that are baked.

[Reference](https://secure.helpscout.net/conversation/453423686/61625?folderId=30784)

**Comment by bogdanap** [comment]
We are already including the latest version of lein in our build images, so for the latest ones, it is indeed 2.8.1: https://travis-ci.org/bogdanap/travis_production_test/jobs/302400545
