### ISSUE TITLE
Consider having Python 3.6 pre-installed in our images

### ISSUE THREAD

**Issue by cotsog** [travis-ci/travis-cookbooks#927]
Since it's the latest Python version, it would be nice to have it pre-installed on our images. It would shave around 30 seconds from builds using it.

This was coming from this support ticket => https://secure.helpscout.net/conversation/443562507/60747/.

Thank you!

**Comment by BanzaiMan** [comment]
This should be the case already: https://github.com/travis-ci/travis-cookbooks/blob/4c3e19997e7153adcd7b8c1b2d7b713e2c83eb22/cookbooks/travis_build_environment/attributes/default.rb#L80

I would argue, though, that we should have 3.5 as well as 3.6.

**Comment by bogdanap** [comment]
This will indeed be included in our next update.
