### ISSUE TITLE
Upgrade the nodejs nvm versions of cookbook

### ISSUE THREAD

**Issue by chenrui333** [travis-ci/travis-cookbooks#986]
I saw the [last commit](https://github.com/travis-ci/travis-cookbooks/commit/55ee3377462d14709eafb88a4c765ec9c3d4d698) was back in Nov 2017, which means it has not been upgraded in the last 1.5 years. 

Do we have plan to do the upgrade any time soon?

Thanks!

**Comment by ljharb** [comment]
@chenrui333 it's not necessary, since on every travis deploy, the latest version of nvm is now automatically downloaded.

You can verify by checking your build log; it prints out `nvm --version`.

**Comment by chenrui333** [comment]
Below are the info I have got from the worker, are you referring to it?

```
Pre-installed Node.js versions
v4.8.6
v6.12.0
v6.12.1
v8.9
v8.9.1

nvm version
0.33.6
```

**Comment by ljharb** [comment]
I’m referring to the actual build log on a travis job
